#%RAML 1.0 Trait

headers:
  client_id:
    type: string
  client_secret:
    type: string
responses:
  401:
    description: Unauthorized or invalid client application credentials
  500:
    description: Bad response from authorization server, or WSDL SOAP Fault error