#%RAML 1.0 Library
usage: This library encapsulates all data types and provides a standard, common format

types:
  account:
    properties:
      firstName?: string
      lastName?: string
      address?: string
    example: !include examples/accountExample.raml

  shipment:
    properties:
      shipmentNumber?: string
      orderNumber?: integer
    example: !include examples/shipmentExample.raml