#%RAML 1.0 NamedExample
error:
  errorCode: NOT FOUND
  errorDateTime: 2019-08-02T16:58:12.121Z
  errorMessage: The resource '/customer/12345678' could not be located
  errorDescription: The requested resource does not exist