#%RAML 1.0 NamedExample
error:
  errorCode: CONFLICT
  errorDateTime: 2019-08-02T16:58:12.121Z
  errorMessage: The resource '/customer/12345678' could not be deleted
  errorDescription: The requested resource could not be modified