#%RAML 1.0 NamedExample
error:
  errorCode: SERVER ERROR
  errorDateTime: 2019-08-02T16:58:12.121Z
  errorMessage: The request could not be completed due to an internal error. You may wish to try again
  errorDescription: Internal server error